
version: "3.6"
 
services:
  douban-img:
    image: douban-img-proxy:latest
    build: .
    restart: always
    container_name: douban-image
    ports:
      - 8088:8081
    volumes:
      - ./cover:/var/www/html/cover
